// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package securityexceptionitems

import (
	"context"
	"encoding/json"
	"time"

	"github.com/elastic/terraform-provider-elasticstack/generated/kbapi"
	"github.com/elastic/terraform-provider-elasticstack/internal/clients"
	"github.com/elastic/terraform-provider-elasticstack/internal/clients/kibanaoapi"
	"github.com/elastic/terraform-provider-elasticstack/internal/entitycore"
	shared "github.com/elastic/terraform-provider-elasticstack/internal/kibana/securityexceptionshared"
	"github.com/elastic/terraform-provider-elasticstack/internal/utils/typeutils"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ExceptionItemsModel is the Terraform state model for the bulk exception items resource.
type ExceptionItemsModel struct {
	entitycore.ResourceTimeoutsField
	ID               types.String `tfsdk:"id"`
	KibanaConnection types.List   `tfsdk:"kibana_connection"`
	SpaceID          types.String `tfsdk:"space_id"`
	ListID           types.String `tfsdk:"list_id"`
	NamespaceType    types.String `tfsdk:"namespace_type"`
	Items            types.List   `tfsdk:"items"`
}

func (m ExceptionItemsModel) GetID() types.String { return m.ID }
func (m ExceptionItemsModel) GetResourceID() types.String {
	return m.ListID
}
func (m ExceptionItemsModel) GetSpaceID() types.String        { return m.SpaceID }
func (m ExceptionItemsModel) GetKibanaConnection() types.List { return m.KibanaConnection }

var _ entitycore.KibanaResourceModel = ExceptionItemsModel{}

// BulkItemModel represents a single exception item within the bulk resource.
type BulkItemModel struct {
	// User-defined identity (may be auto-generated by Kibana if omitted)
	ItemID      types.String         `tfsdk:"item_id"`
	Type        types.String         `tfsdk:"type"`
	Name        types.String         `tfsdk:"name"`
	Description types.String         `tfsdk:"description"`
	Entries     types.List           `tfsdk:"entries"`
	OsTypes     types.Set            `tfsdk:"os_types"`
	Tags        types.Set            `tfsdk:"tags"`
	Meta        jsontypes.Normalized `tfsdk:"meta"`
	ExpireTime  timetypes.RFC3339    `tfsdk:"expire_time"`
	Comments    types.List           `tfsdk:"comments"`

	// Computed fields populated by Kibana after create/read
	ID           types.String `tfsdk:"id"`
	Version      types.String `tfsdk:"_version"`
	TieBreakerID types.String `tfsdk:"tie_breaker_id"`
	CreatedAt    types.String `tfsdk:"created_at"`
	CreatedBy    types.String `tfsdk:"created_by"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
	UpdatedBy    types.String `tfsdk:"updated_by"`
}

// bulkItemAttrTypes returns the Terraform attribute types for a BulkItemModel.
func bulkItemAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"item_id":        types.StringType,
		"type":           types.StringType,
		"name":           types.StringType,
		"description":    types.StringType,
		"entries":        types.ListType{ElemType: types.ObjectType{AttrTypes: shared.GetEntryAttrTypes()}},
		"os_types":       types.SetType{ElemType: types.StringType},
		"tags":           types.SetType{ElemType: types.StringType},
		"meta":           jsontypes.NormalizedType{},
		"expire_time":    timetypes.RFC3339Type{},
		"comments":       types.ListType{ElemType: types.ObjectType{AttrTypes: shared.GetCommentAttrTypes()}},
		"id":             types.StringType,
		"_version":       types.StringType,
		"tie_breaker_id": types.StringType,
		"created_at":     types.StringType,
		"created_by":     types.StringType,
		"updated_at":     types.StringType,
		"updated_by":     types.StringType,
	}
}

// planItems extracts the list of BulkItemModel from the plan/state.
func planItems(ctx context.Context, m ExceptionItemsModel) ([]BulkItemModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	if !typeutils.IsKnown(m.Items) {
		return nil, diags
	}
	items := typeutils.ListTypeAs[BulkItemModel](ctx, m.Items, path.Empty(), &diags)
	return items, diags
}

// setItems writes a slice of BulkItemModel back into the model.
func setItems(ctx context.Context, m *ExceptionItemsModel, items []BulkItemModel) diag.Diagnostics {
	list, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: bulkItemAttrTypes()}, items)
	m.Items = list
	return diags
}

// itemBulkModel converts a BulkItemModel to a bulk create request item.
func itemToBulkCreateRequest(ctx context.Context, item BulkItemModel) (kibanaoapi.ExceptionItemBulkCreateItemRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	entries, d := shared.ConvertEntriesToAPI(ctx, item.Entries)
	diags.Append(d...)
	if diags.HasError() {
		return kibanaoapi.ExceptionItemBulkCreateItemRequest{}, diags
	}

	req := kibanaoapi.ExceptionItemBulkCreateItemRequest{
		Type:        item.Type.ValueString(),
		Name:        item.Name.ValueString(),
		Description: item.Description.ValueString(),
		Entries:     entries,
	}

	id := item.ItemID.ValueString()
	req.ItemID = &id

	if typeutils.IsKnown(item.OsTypes) {
		osTypes := typeutils.SetTypeAs[string](ctx, item.OsTypes, path.Empty(), &diags)
		if !diags.HasError() {
			req.OsTypes = osTypes
		}
	}

	if typeutils.IsKnown(item.Tags) {
		tags := typeutils.SetTypeAs[string](ctx, item.Tags, path.Empty(), &diags)
		if !diags.HasError() {
			req.Tags = tags
		}
	}

	if typeutils.IsKnown(item.Meta) && !item.Meta.IsNull() {
		var meta map[string]any
		if err := json.Unmarshal([]byte(item.Meta.ValueString()), &meta); err == nil {
			req.Meta = meta
		}
	}

	if typeutils.IsKnown(item.ExpireTime) && !item.ExpireTime.IsNull() {
		t, d := item.ExpireTime.ValueRFC3339Time()
		diags.Append(d...)
		if !diags.HasError() {
			s := t.Format("2006-01-02T15:04:05.000Z")
			req.ExpireTime = &s
		}
	}

	if typeutils.IsKnown(item.Comments) {
		comments := typeutils.ListTypeAs[shared.CommentModel](ctx, item.Comments, path.Empty(), &diags)
		if !diags.HasError() {
			for _, c := range comments {
				req.Comments = append(req.Comments, kibanaoapi.ExceptionItemBulkComment{
					Comment: c.Comment.ValueString(),
				})
			}
		}
	}

	return req, diags
}

// itemToBulkUpdateRequest converts a BulkItemModel to a bulk update request item.
func itemToBulkUpdateRequest(ctx context.Context, item BulkItemModel) (kibanaoapi.ExceptionItemBulkUpdateItemRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	entries, d := shared.ConvertEntriesToAPI(ctx, item.Entries)
	diags.Append(d...)
	if diags.HasError() {
		return kibanaoapi.ExceptionItemBulkUpdateItemRequest{}, diags
	}

	req := kibanaoapi.ExceptionItemBulkUpdateItemRequest{
		ID:          item.ID.ValueString(),
		Type:        item.Type.ValueString(),
		Name:        item.Name.ValueString(),
		Description: item.Description.ValueString(),
		Entries:     entries,
	}

	if typeutils.IsKnown(item.Version) && !item.Version.IsNull() {
		v := item.Version.ValueString()
		req.Version = &v
	}

	if typeutils.IsKnown(item.OsTypes) {
		osTypes := typeutils.SetTypeAs[string](ctx, item.OsTypes, path.Empty(), &diags)
		if !diags.HasError() {
			req.OsTypes = osTypes
		}
	}

	if typeutils.IsKnown(item.Tags) {
		tags := typeutils.SetTypeAs[string](ctx, item.Tags, path.Empty(), &diags)
		if !diags.HasError() {
			req.Tags = tags
		}
	}

	if typeutils.IsKnown(item.Meta) && !item.Meta.IsNull() {
		var meta map[string]any
		if err := json.Unmarshal([]byte(item.Meta.ValueString()), &meta); err == nil {
			req.Meta = meta
		}
	}

	if typeutils.IsKnown(item.ExpireTime) && !item.ExpireTime.IsNull() {
		t, d := item.ExpireTime.ValueRFC3339Time()
		diags.Append(d...)
		if !diags.HasError() {
			s := t.Format("2006-01-02T15:04:05.000Z")
			req.ExpireTime = &s
		}
	}

	if typeutils.IsKnown(item.Comments) {
		comments := typeutils.ListTypeAs[shared.CommentModel](ctx, item.Comments, path.Empty(), &diags)
		if !diags.HasError() {
			for _, c := range comments {
				var cID *string
				if typeutils.IsKnown(c.ID) && !c.ID.IsNull() {
					id := c.ID.ValueString()
					cID = &id
				}
				req.Comments = append(req.Comments, kibanaoapi.ExceptionItemBulkUpdateComment{
					ID:      cID,
					Comment: c.Comment.ValueString(),
				})
			}
		}
	}

	return req, diags
}

// itemFromAPI converts an API exception list item to a BulkItemModel.
func itemFromAPI(ctx context.Context, apiItem kbapi.SecurityExceptionsAPIExceptionListItem, prior *BulkItemModel) (BulkItemModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var item BulkItemModel

	item.ID = typeutils.StringishValue(apiItem.Id)
	item.ItemID = typeutils.StringishValue(apiItem.ItemId)
	item.Type = typeutils.StringishValue(apiItem.Type)
	item.Name = typeutils.StringishValue(apiItem.Name)
	item.Description = typeutils.StringishValue(apiItem.Description)
	item.TieBreakerID = types.StringValue(apiItem.TieBreakerId)
	item.CreatedAt = types.StringValue(apiItem.CreatedAt.Format("2006-01-02T15:04:05.000Z"))
	item.CreatedBy = types.StringValue(apiItem.CreatedBy)
	item.UpdatedAt = types.StringValue(apiItem.UpdatedAt.Format("2006-01-02T15:04:05.000Z"))
	item.UpdatedBy = types.StringValue(apiItem.UpdatedBy)

	if apiItem.UnderscoreVersion != nil {
		item.Version = types.StringValue(*apiItem.UnderscoreVersion)
	} else {
		item.Version = types.StringNull()
	}

	if apiItem.ExpireTime != nil {
		t, err := time.Parse(time.RFC3339, *apiItem.ExpireTime)
		if err != nil {
			diags.AddError("Failed to parse expire_time", err.Error())
			item.ExpireTime = timetypes.NewRFC3339Null()
		} else {
			item.ExpireTime = timetypes.NewRFC3339TimeValue(t)
		}
	} else {
		item.ExpireTime = timetypes.NewRFC3339Null()
	}

	if apiItem.OsTypes != nil && len(*apiItem.OsTypes) > 0 {
		set, d := types.SetValueFrom(ctx, types.StringType, *apiItem.OsTypes)
		diags.Append(d...)
		item.OsTypes = set
	} else {
		if prior != nil && !prior.OsTypes.IsUnknown() {
			item.OsTypes = prior.OsTypes
		} else {
			item.OsTypes = types.SetNull(types.StringType)
		}
	}

	if apiItem.Tags != nil && len(*apiItem.Tags) > 0 {
		set, d := types.SetValueFrom(ctx, types.StringType, *apiItem.Tags)
		diags.Append(d...)
		item.Tags = set
	} else {
		if prior != nil && !prior.Tags.IsUnknown() {
			item.Tags = prior.Tags
		} else {
			item.Tags = types.SetNull(types.StringType)
		}
	}

	if apiItem.Meta != nil {
		metaBytes, err := json.Marshal(apiItem.Meta)
		if err != nil {
			diags.AddError("Failed to marshal meta", err.Error())
			item.Meta = jsontypes.NewNormalizedNull()
		} else {
			item.Meta = jsontypes.NewNormalizedValue(string(metaBytes))
		}
	} else {
		item.Meta = jsontypes.NewNormalizedNull()
	}

	entriesList, d := shared.ConvertEntriesFromAPI(ctx, apiItem.Entries)
	diags.Append(d...)
	item.Entries = entriesList

	if len(apiItem.Comments) > 0 {
		comments := make([]shared.CommentModel, len(apiItem.Comments))
		for i, c := range apiItem.Comments {
			comments[i] = shared.CommentModel{
				ID:      typeutils.StringishValue(c.Id),
				Comment: typeutils.StringishValue(c.Comment),
			}
		}
		list, d := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: shared.GetCommentAttrTypes()}, comments)
		diags.Append(d...)
		item.Comments = list
	} else {
		item.Comments = types.ListNull(types.ObjectType{AttrTypes: shared.GetCommentAttrTypes()})
	}

	return item, diags
}

// diffItems returns three slices: items to create, items to update, item IDs to delete.
// Items are matched by item_id, which is required on the schema so every plan item has one.
func diffItems(
	planItems []BulkItemModel,
	stateItems []BulkItemModel,
) (toCreate []BulkItemModel, toUpdate []BulkItemModel, toDeleteIDs []string) {
	stateByItemID := make(map[string]BulkItemModel, len(stateItems))
	for _, s := range stateItems {
		if id := s.ItemID.ValueString(); id != "" {
			stateByItemID[id] = s
		}
	}

	planByItemID := make(map[string]BulkItemModel, len(planItems))
	for _, p := range planItems {
		if id := p.ItemID.ValueString(); id != "" {
			planByItemID[id] = p
		}
	}

	// Plan items: create if new, update if already in state.
	for itemID, p := range planByItemID {
		if s, exists := stateByItemID[itemID]; exists {
			// Copy computed fields from state so the bulk update carries the right ID and version.
			p.ID = s.ID
			p.Version = s.Version
			toUpdate = append(toUpdate, p)
		} else {
			toCreate = append(toCreate, p)
		}
	}

	// State items not in plan → delete.
	for itemID, s := range stateByItemID {
		if _, inPlan := planByItemID[itemID]; !inPlan {
			if id := s.ID.ValueString(); id != "" {
				toDeleteIDs = append(toDeleteIDs, id)
			}
		}
	}

	return toCreate, toUpdate, toDeleteIDs
}

// buildCompositeID builds the composite ID for the bulk resource: <spaceID>/<listID>
func buildCompositeID(spaceID, listID string) string {
	return (&clients.CompositeID{ClusterID: spaceID, ResourceID: listID}).String()
}
